### ISSUE TITLE
Probleme css custom

### ISSUE THREAD

**Issue by xorgxx** [msalsas/MsalsasGdprConsentBannerBundle#1]
Hi i just have try you bundle with SF 5 and i have same trouble with custom css.

i have set in config.yaml my css and it das not wanted to show off it take your as import not my.
```
msalsas_gdpr_consent_banner:
    css: build/css/app.css # [default|none]
    has_translations: true # [true|false]
    text_message: '' # [{message}|{key}]
    accept_message: '' # [{message}|{key}]
    fade_time: 2
    time_to_expire: 30 days
```
thank for your help
